import path from "node:path";

import { parsePortableDocument } from "../catalog/frontmatter.js";
import type { PlannedFile } from "../core/contracts.js";
import { ForgeyardError } from "../core/errors.js";
import { canonicalJson } from "../core/hash.js";

export type HarnessLintRule =
  | "dangling-reference"
  | "orphan-reference"
  | "absolute-path-leak"
  | "unresolved-placeholder"
  | "context-budget-exceeded"
  | "duplicate-authority"
  | "empty-instruction"
  | "volatile-reference";

export type HarnessLintSeverity = "blocking" | "important" | "informational";

export type HarnessLintOwnership = "generated" | "vendored";

export interface HarnessLintFinding {
  rule: HarnessLintRule;
  severity: HarnessLintSeverity;
  /** Vendored findings are disclosed but never reject a plan: their bytes are not ours to repair. */
  ownership: HarnessLintOwnership;
  path: string;
  detail: string;
  subject?: string;
}

export interface HarnessLintOptions {
  /** Byte ceiling for a root instruction file (CLAUDE.md, AGENTS.md). Default 32768. */
  rootCeilingBytes?: number;
  /** Byte ceiling for any other generated instruction/skill file. Default 16384. */
  fileCeilingBytes?: number;
  /** Paths the plan may reference without installing them, e.g. pre-existing project files. */
  externalPaths?: readonly string[];
  /** Component id prefixes whose bytes Forgeyard preserves verbatim under their own license. Default ["ecosystem."]. */
  vendoredComponentPrefixes?: readonly string[];
}

export interface HarnessLintReport {
  status: "clean" | "warned" | "rejected";
  findings: readonly HarnessLintFinding[];
  counts: Readonly<Record<HarnessLintSeverity, number>>;
  /** Blocking findings on generated bytes. Only these reject the plan. */
  generatedBlocking: number;
  budget: {
    largestPath: string | null;
    largestBytes: number;
    rootCeilingBytes: number;
    fileCeilingBytes: number;
  };
}

const DEFAULT_ROOT_CEILING_BYTES = 32_768;
const DEFAULT_FILE_CEILING_BYTES = 16_384;
const DEFAULT_VENDORED_PREFIXES: readonly string[] = ["ecosystem."];
const MINIMUM_ACTIONABLE_CHARACTERS = 32;

const SEVERITY_ORDER: readonly HarnessLintSeverity[] = ["blocking", "important", "informational"];
/** Actionable findings come first: the reader can only repair generated bytes. */
const OWNERSHIP_ORDER: readonly HarnessLintOwnership[] = ["generated", "vendored"];

const RULE_SEVERITY: Readonly<Record<HarnessLintRule, HarnessLintSeverity>> = {
  "absolute-path-leak": "blocking",
  "dangling-reference": "blocking",
  "duplicate-authority": "blocking",
  "unresolved-placeholder": "blocking",
  "context-budget-exceeded": "important",
  "empty-instruction": "important",
  "orphan-reference": "important",
  "volatile-reference": "important",
};

/** Directory prefixes that name the harness itself, and are therefore project-relative. */
const HARNESS_ROOTS: readonly string[] = [".claude/", ".codex/", ".agents/", ".forgeyard/"];

const MARKDOWN_LINK = /\[[^\]\n]*\]\(\s*<?([^()<>\s]+)>?(?:\s+"[^"\n]*")?\s*\)/g;
const WIKI_LINK = /\[\[\s*([^[\]|\n]+?)\s*(?:\|[^[\]\n]*)?\]\]/g;
const HARNESS_MENTION = /(?<![\w./\\-])\.(?:claude|codex|agents|forgeyard)\/[\w./-]*\.[A-Za-z0-9]+/g;
const WINDOWS_ABSOLUTE = /(?<![A-Za-z0-9])[A-Za-z]:[\\/][^\s"'`<>|*?()[\]{}]*/g;
const POSIX_ABSOLUTE = /(?<![\w.:/\\-])\/(?:Users|home|root)\/[^\s"'`<>|*?()[\]{}]*/g;
const PLACEHOLDER = /\{\{[^{}]*\}\}/g;
const COMMIT_SHA = /\b[0-9a-f]{7,64}\b/g;
const LINE_REFERENCE = /(?<![\w./\\-])[\w-]+(?:[/.][\w-]+)*\.[A-Za-z0-9]+(?::\d+|#L\d+(?:-L?\d+)?)/g;
const HTML_COMMENT = /<!--[\s\S]*?-->/g;
const URI_SCHEME = /^[A-Za-z][A-Za-z0-9+.-]*:/;
const TRAILING_PUNCTUATION = /[.,;:!?]+$/;

interface ExtractedReference {
  /** The reference exactly as authored, used as the finding subject. */
  reference: string;
  /** Project-relative candidates, most canonical first. */
  candidates: readonly string[];
  kind: "path" | "wiki";
}

function isMarkdown(filePath: string): boolean {
  return filePath.toLocaleLowerCase("en-US").endsWith(".md");
}

function isRootInstruction(filePath: string): boolean {
  return !filePath.includes("/");
}

function byteLength(content: string): number {
  return Buffer.byteLength(content, "utf8");
}

function portablePath(candidate: string): string {
  const normalized = path.posix.normalize(candidate.replaceAll("\\", "/"));
  if (normalized === "." || normalized === "./") return "";
  return normalized.replace(/^\.\//, "").replace(/\/+$/, "");
}

function parentDirectory(filePath: string): string {
  const index = filePath.lastIndexOf("/");
  return index < 0 ? "" : filePath.slice(0, index);
}

function harnessRooted(reference: string): boolean {
  return HARNESS_ROOTS.some((root) => reference.startsWith(root));
}

function resolveFrom(directory: string, reference: string): string {
  if (harnessRooted(reference)) return portablePath(reference);
  return portablePath(directory === "" ? reference : `${directory}/${reference}`);
}

function escapesRoot(candidate: string): boolean {
  return candidate === ".." || candidate.startsWith("../");
}

/** Removes fenced code blocks, where an example command legitimately carries a volatile value. */
function stripFencedBlocks(content: string): string {
  const kept: string[] = [];
  let fence: string | null = null;

  for (const line of content.replaceAll("\r\n", "\n").split("\n")) {
    const marker = /^\s{0,3}(`{3,}|~{3,})/.exec(line)?.[1];
    if (fence === null) {
      if (marker === undefined) kept.push(line);
      else fence = marker.slice(0, 1);
      continue;
    }
    if (marker !== undefined && marker.startsWith(fence)) fence = null;
  }

  return kept.join("\n");
}

function matches(content: string, pattern: RegExp): readonly string[] {
  return [...content.matchAll(pattern)].map((match) => match[0]);
}

function readDocument(file: PlannedFile): { name: string | null; body: string } {
  if (!isMarkdown(file.path)) return { name: null, body: file.content };
  try {
    const parsed = parsePortableDocument(file.content, file.path);
    const declared = parsed.frontmatter.name;
    const name = typeof declared === "string" && declared.trim().length > 0 ? declared.trim() : null;
    return { name, body: parsed.body };
  } catch {
    // A malformed frontmatter block is the adapter's failure, not an incoherent reference.
    return { name: null, body: file.content };
  }
}

function extractReferences(file: PlannedFile): readonly ExtractedReference[] {
  const directory = parentDirectory(portablePath(file.path));
  const found: ExtractedReference[] = [];

  for (const match of file.content.matchAll(MARKDOWN_LINK)) {
    const target = match[1];
    if (target === undefined) continue;
    if (target.startsWith("#") || target.startsWith("/") || URI_SCHEME.test(target)) continue;
    const bare = target.split("#")[0]?.split("?")[0] ?? "";
    if (bare.length === 0 || bare.endsWith("/")) continue;
    found.push({ reference: bare, candidates: [resolveFrom(directory, bare)], kind: "path" });
  }

  for (const match of file.content.matchAll(WIKI_LINK)) {
    const name = match[1];
    if (name === undefined || name.length === 0 || URI_SCHEME.test(name)) continue;
    found.push({
      reference: name,
      candidates: [resolveFrom(directory, `${name}.md`), resolveFrom(directory, name)],
      kind: "wiki",
    });
  }

  for (const mention of matches(file.content, HARNESS_MENTION)) {
    found.push({ reference: mention, candidates: [portablePath(mention)], kind: "path" });
  }

  return found;
}

function danglingDetail(entry: ExtractedReference): string {
  if (entry.kind === "wiki") {
    return `Wiki-link '[[${entry.reference}]]' does not resolve to a file installed by the plan.`;
  }
  if (entry.candidates.every((candidate) => escapesRoot(candidate))) {
    return `Reference '${entry.reference}' leaves the project root, so it can never resolve to an installed file.`;
  }
  return `Reference '${entry.reference}' resolves to '${entry.candidates[0] ?? ""}', which the plan does not install.`;
}

function volatileSubjects(content: string): readonly string[] {
  // Inside a fenced block both forms are almost always an example command or its output.
  const prose = stripFencedBlocks(content);
  const shas = matches(prose, COMMIT_SHA).filter(
    // A 64 hex run is one of our own evidence digests; a deliberate byte constant carries no
    // hex letter, and an all-hex english word carries no digit.
    (candidate) => candidate.length <= 40 && /\d/.test(candidate) && /[a-f]/.test(candidate),
  );
  return [...shas, ...matches(prose, LINE_REFERENCE)];
}

function volatileDetail(subject: string): string {
  if (/[:#]/.test(subject)) {
    return `Line reference '${subject}' drifts on the next edit, so cite the file path with a symbol name or a section title instead.`;
  }
  return `Commit SHA '${subject}' stops resolving once history is rewritten, so cite a file path, a symbol name or a section title instead.`;
}

function finding(
  rule: HarnessLintRule,
  ownership: HarnessLintOwnership,
  filePath: string,
  detail: string,
  subject?: string,
): HarnessLintFinding {
  return {
    rule,
    severity: RULE_SEVERITY[rule],
    ownership,
    path: filePath,
    detail,
    ...(subject === undefined ? {} : { subject }),
  };
}

function compare(left: HarnessLintFinding, right: HarnessLintFinding): number {
  return (
    SEVERITY_ORDER.indexOf(left.severity) - SEVERITY_ORDER.indexOf(right.severity) ||
    OWNERSHIP_ORDER.indexOf(left.ownership) - OWNERSHIP_ORDER.indexOf(right.ownership) ||
    left.rule.localeCompare(right.rule, "en") ||
    left.path.localeCompare(right.path, "en") ||
    (left.subject ?? "").localeCompare(right.subject ?? "", "en")
  );
}

/** Only a blocking finding on bytes Forgeyard authored has the authority to reject a plan. */
function rejecting(entry: HarnessLintFinding): boolean {
  return entry.severity === "blocking" && entry.ownership === "generated";
}

function deduplicate(findings: readonly HarnessLintFinding[]): readonly HarnessLintFinding[] {
  const unique = new Map<string, HarnessLintFinding>();
  for (const candidate of findings) {
    unique.set(canonicalJson([candidate.rule, candidate.path, candidate.subject ?? null]), candidate);
  }
  return [...unique.values()].sort(compare);
}

export function lintHarness(
  files: readonly PlannedFile[],
  options: HarnessLintOptions = {},
): HarnessLintReport {
  const rootCeilingBytes = options.rootCeilingBytes ?? DEFAULT_ROOT_CEILING_BYTES;
  const fileCeilingBytes = options.fileCeilingBytes ?? DEFAULT_FILE_CEILING_BYTES;
  const vendoredPrefixes = options.vendoredComponentPrefixes ?? DEFAULT_VENDORED_PREFIXES;
  const installed = new Set(files.map((file) => portablePath(file.path)));
  const known = new Set([...installed, ...(options.externalPaths ?? []).map(portablePath)]);
  const findings: HarnessLintFinding[] = [];
  const pointedAt = new Map<string, Set<string>>();
  const byName = new Map<string, string[]>();
  const ownershipByPath = new Map<string, HarnessLintOwnership>(
    files.map((file) => [
      portablePath(file.path),
      vendoredPrefixes.some((prefix) => file.componentId.startsWith(prefix)) ? "vendored" : "generated",
    ]),
  );

  let largestPath: string | null = null;
  let largestBytes = 0;

  for (const file of files) {
    const filePath = portablePath(file.path);
    const ownership = ownershipByPath.get(filePath) ?? "generated";
    const bytes = byteLength(file.content);
    const markdown = isMarkdown(filePath);
    const document = readDocument(file);

    if (
      markdown &&
      (largestPath === null ||
        bytes > largestBytes ||
        (bytes === largestBytes && filePath.localeCompare(largestPath, "en") < 0))
    ) {
      largestPath = filePath;
      largestBytes = bytes;
    }

    for (const placeholder of matches(file.content, PLACEHOLDER)) {
      findings.push(
        finding(
          "unresolved-placeholder",
          ownership,
          filePath,
          `Template marker '${placeholder}' survived rendering and was never replaced by a value.`,
          placeholder,
        ),
      );
    }

    for (const leak of [
      ...matches(file.content, WINDOWS_ABSOLUTE),
      ...matches(file.content, POSIX_ABSOLUTE),
    ]) {
      const subject = leak.replace(TRAILING_PUNCTUATION, "");
      if (subject.length === 0) continue;
      findings.push(
        finding(
          "absolute-path-leak",
          ownership,
          filePath,
          `Machine-absolute path '${subject}' survived into generated content and will not exist on another machine.`,
          subject,
        ),
      );
    }

    if (!markdown) continue;

    if (document.name !== null) {
      const claimants = byName.get(document.name) ?? [];
      claimants.push(filePath);
      byName.set(document.name, claimants);
    }

    for (const subject of volatileSubjects(file.content)) {
      findings.push(finding("volatile-reference", ownership, filePath, volatileDetail(subject), subject));
    }

    const ceiling = isRootInstruction(filePath) ? rootCeilingBytes : fileCeilingBytes;
    if (bytes > ceiling) {
      const scope = isRootInstruction(filePath) ? "root instruction file" : "generated instruction file";
      findings.push(
        finding(
          "context-budget-exceeded",
          ownership,
          filePath,
          `Instruction file '${filePath}' is ${bytes} bytes, above the ${ceiling} byte ceiling for a ${scope}.`,
          String(bytes),
        ),
      );
    }

    const actionable = document.body.replaceAll(HTML_COMMENT, "").replaceAll(/\s+/g, "");
    if (actionable.length < MINIMUM_ACTIONABLE_CHARACTERS) {
      findings.push(
        finding(
          "empty-instruction",
          ownership,
          filePath,
          `Instruction file '${filePath}' carries no actionable content once frontmatter, HTML comments and whitespace are removed.`,
        ),
      );
    }

    for (const entry of extractReferences(file)) {
      if (entry.candidates.some((candidate) => known.has(candidate))) {
        for (const candidate of entry.candidates) {
          const sources = pointedAt.get(candidate) ?? new Set<string>();
          sources.add(filePath);
          pointedAt.set(candidate, sources);
        }
        continue;
      }
      findings.push(
        finding("dangling-reference", ownership, filePath, danglingDetail(entry), entry.reference),
      );
    }
  }

  for (const [name, claimants] of byName) {
    if (claimants.length < 2) continue;
    for (const claimant of claimants) {
      findings.push(
        finding(
          "duplicate-authority",
          ownershipByPath.get(claimant) ?? "generated",
          claimant,
          `Component name '${name}' is declared by more than one generated file, so one of them wins silently.`,
          name,
        ),
      );
    }
  }

  for (const filePath of installed) {
    if (!filePath.split("/").includes("references")) continue;
    const sources = [...(pointedAt.get(filePath) ?? new Set<string>())].filter(
      (source) => source !== filePath,
    );
    if (sources.length > 0) continue;
    findings.push(
      finding(
        "orphan-reference",
        ownershipByPath.get(filePath) ?? "generated",
        filePath,
        `Reference file '${filePath}' is installed but no other generated file points to it.`,
      ),
    );
  }

  const ordered = deduplicate(findings);
  const counts: Record<HarnessLintSeverity, number> = { blocking: 0, important: 0, informational: 0 };
  for (const entry of ordered) counts[entry.severity] += 1;
  const generatedBlocking = ordered.filter(rejecting).length;

  return {
    status: generatedBlocking > 0 ? "rejected" : ordered.length > 0 ? "warned" : "clean",
    findings: ordered,
    counts,
    generatedBlocking,
    budget: { largestPath, largestBytes, rootCeilingBytes, fileCeilingBytes },
  };
}

export function assertHarnessAccepted(report: HarnessLintReport): void {
  if (report.status !== "rejected") return;

  const paths = [...new Set(report.findings.filter(rejecting).map((entry) => entry.path))].sort(
    (left, right) => left.localeCompare(right, "en"),
  );

  throw new ForgeyardError({
    code: "FY_HARNESS_INCOHERENT",
    message: "The generated harness is incoherent and has not been installed.",
    remediation: "Fix the blocking harness findings and plan the installation again.",
    exitCode: 9,
    paths,
  });
}
